/**
 * Phase F — Lightpanda POC executor.
 *
 * Runs POCs that need a real browser engine (DOM-based XSS, client-side
 * validation bypass) via Lightpanda's headless browser. Generates a
 * PandaScript, runs it with `lightpanda agent <script.js>` (no LLM, no
 * API key — deterministic replay), and parses the JSON output.
 *
 * Lightpanda is optional: if the binary is not on PATH, the executor
 * returns a "not verified" result with install instructions. The
 * existing SandboxRunner handles HTTP-based POCs independently.
 *
 * Install: curl -fsSL https://pkg.lightpanda.io/install.sh | bash
 * Docs: https://lightpanda.io/docs
 */

import { execSync, spawn } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import type { PocRequest, PocResult } from './pocTypes';

// ── Binary detection ────────────────────────────────────────────────────────

let _available: boolean | null = null;

/**
 * Check if the Lightpanda binary is on PATH. Memoized — the check runs
 * execSync which is expensive, so we cache the result for the process
 * lifetime.
 */
export function isLightpandaAvailable(): boolean {
    if (_available !== null) return _available;
    try {
        execSync('lightpanda --version', { stdio: 'ignore', timeout: 5000 } as any);
        _available = true;
    } catch {
        _available = false;
    }
    return _available;
}

/** Reset the availability cache (for tests). */
export function _resetAvailabilityCache(): void {
    _available = null;
}

// ── PandaScript generation ──────────────────────────────────────────────────

/**
 * Generate a PandaScript for the given POC request.
 *
 * The script uses Lightpanda's native page API (goto, fill, click, extract)
 * — no LLM at runtime. The last expression auto-prints as JSON.
 */
export function generatePandaScript(req: PocRequest): string {
    const baseUrl = req.endpoint.baseUrl || 'http://127.0.0.1:3000';
    const fullPath = req.endpoint.path.startsWith('/')
        ? req.endpoint.path
        : '/' + req.endpoint.path;
    const url = baseUrl + fullPath;
    const payload = req.payload || '<script>alert(1)</script>';

    // XSS: navigate to the endpoint with the payload, check if it appears
    // unescaped in the rendered DOM.
    if (req.vulnType === 'xss') {
        const injectionPoint = req.injectionPoint || 'query';
        const paramName = req.paramName || 'q';

        if (injectionPoint === 'query') {
            // Query parameter injection: navigate directly to the URL with payload
            const injectUrl = `${url}${url.includes('?') ? '&' : '?'}${paramName}=${encodeURIComponent(payload)}`;
            return [
                `// PandaScript — XSS POC (query injection)`,
                `// Generated by SecureCode Phase F`,
                `const page = new Page();`,
                `await page.goto(${JSON.stringify(injectUrl)});`,
                `const result = page.extract([{ selector: 'body', fields: { content: '' } }]);`,
                `const bodyContent = result[0]?.content || '';`,
                `const payload = ${JSON.stringify(payload)};`,
                `const exploited = bodyContent.includes(payload);`,
                `return { exploited, evidence: exploited ? 'Payload found unescaped in rendered DOM' : 'Payload not found in DOM (may be sanitized)' };`,
            ].join('\n');
        }

        if (injectionPoint === 'body') {
            // Body injection: fill a form field and submit
            return [
                `// PandaScript — XSS POC (body injection)`,
                `// Generated by SecureCode Phase F`,
                `const page = new Page();`,
                `await page.goto(${JSON.stringify(url)});`,
                `await page.fill('input[name=${JSON.stringify(paramName)}], input[type="text"], textarea', ${JSON.stringify(payload)});`,
                `await page.click('button[type="submit"], input[type="submit"], button');`,
                `const result = page.extract([{ selector: 'body', fields: { content: '' } }]);`,
                `const bodyContent = result[0]?.content || '';`,
                `const payload = ${JSON.stringify(payload)};`,
                `const exploited = bodyContent.includes(payload);`,
                `return { exploited, evidence: exploited ? 'Payload found unescaped in rendered DOM after form submission' : 'Payload not found in DOM (may be sanitized or form selector mismatch)' };`,
            ].join('\n');
        }

        // Default: navigate directly and check
        return [
            `// PandaScript — XSS POC (direct navigation)`,
            `const page = new Page();`,
            `await page.goto(${JSON.stringify(url)});`,
            `const result = page.extract([{ selector: 'body', fields: { content: '' } }]);`,
            `const bodyContent = result[0]?.content || '';`,
            `const payload = ${JSON.stringify(payload)};`,
            `const exploited = bodyContent.includes(payload);`,
            `return { exploited, evidence: exploited ? 'Payload found in DOM' : 'Payload not found in DOM' };`,
        ].join('\n');
    }

    // Open redirect: navigate and check the final URL
    if (req.vulnType === 'open_redirect') {
        const paramName = req.paramName || 'url';
        const redirectUrl = `${url}${url.includes('?') ? '&' : '?'}${paramName}=${encodeURIComponent(req.payload || 'https://evil.com')}`;
        return [
            `// PandaScript — Open Redirect POC`,
            `const page = new Page();`,
            `await page.goto(${JSON.stringify(redirectUrl)});`,
            `const finalUrl = page.getUrl();`,
            `const target = ${JSON.stringify(req.payload || 'https://evil.com')};`,
            `const exploited = finalUrl.includes(target);`,
            `return { exploited, evidence: exploited ? 'Redirected to ' + finalUrl : 'Did not redirect to target (stayed at ' + finalUrl + ')' };`,
        ].join('\n');
    }

    // Generic fallback: navigate and extract page content
    return [
        `// PandaScript — Generic POC`,
        `const page = new Page();`,
        `await page.goto(${JSON.stringify(url)});`,
        `const result = page.extract([{ selector: 'body', fields: { content: '' } }]);`,
        `return { exploited: false, evidence: 'No specific POC pattern for ${req.vulnType}; page content: ' + (result[0]?.content || '').slice(0, 500) };`,
    ].join('\n');
}

// ── Execution ───────────────────────────────────────────────────────────────

/**
 * Execute a POC using Lightpanda.
 *
 * Generates a PandaScript, writes it to a temp file, runs
 * `lightpanda agent <script.js>` (no LLM, deterministic), and parses the
 * JSON output.
 *
 * Returns a "not verified" result when Lightpanda is not installed.
 */
export async function executeWithLightpanda(req: PocRequest): Promise<PocResult> {
    if (!isLightpandaAvailable()) {
        return {
            exploitable: false,
            timedOut: false,
            evidence: 'Lightpanda binary not found on PATH. Install: curl -fsSL https://pkg.lightpanda.io/install.sh | bash',
            backend: 'none',
        };
    }

    const script = generatePandaScript(req);
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'securecode-poc-'));
    const scriptPath = path.join(tmpDir, 'poc.js');

    try {
        fs.writeFileSync(scriptPath, script, 'utf8');

        // Run the PandaScript with Lightpanda (no LLM, no API key)
        const result = await new Promise<PocResult>((resolve) => {
            const child = spawn('lightpanda', ['agent', scriptPath], {
                stdio: ['pipe', 'pipe', 'pipe'],
                shell: true,
                timeout: 10_000,  // 10s timeout
            });

            let stdout = '';
            let stderr = '';
            let timedOut = false;

            child.stdout?.on('data', (chunk: Buffer) => { stdout += chunk.toString(); });
            child.stderr?.on('data', (chunk: Buffer) => { stderr += chunk.toString(); });

            child.on('close', (code) => {
                if (timedOut) return;  // timeout handler already resolved
                try {
                    // Lightpanda agent prints the last expression as JSON to stdout
                    const output = stdout.trim();
                    const parsed = JSON.parse(output);
                    resolve({
                        exploitable: Boolean(parsed.exploited),
                        output: parsed.evidence || output,
                        timedOut: false,
                        evidence: parsed.evidence || 'POC executed via Lightpanda',
                        pocScript: script,
                        backend: 'lightpanda',
                    });
                } catch {
                    resolve({
                        exploitable: false,
                        output: stdout.slice(0, 500),
                        error: stderr.slice(0, 500) || 'Failed to parse Lightpanda output',
                        timedOut: false,
                        evidence: 'Lightpanda ran but the output was not parseable JSON',
                        pocScript: script,
                        backend: 'lightpanda',
                    });
                }
            });

            child.on('error', (err) => {
                resolve({
                    exploitable: false,
                    error: err.message,
                    timedOut: false,
                    evidence: `Lightpanda failed to start: ${err.message}`,
                    pocScript: script,
                    backend: 'lightpanda',
                });
            });

            const timer = setTimeout(() => {
                timedOut = true;
                child.kill('SIGKILL');
                resolve({
                    exploitable: false,
                    timedOut: true,
                    evidence: 'POC timed out after 10s',
                    pocScript: script,
                    backend: 'lightpanda',
                });
            }, 10_000);
            timer.unref?.();
        });

        return result;
    } finally {
        try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* best-effort */ }
    }
}
